import { z } from "zod";

// Course Validation Schema
export const courseSchema = z.object({
  id: z.string().optional(), // usually auto-generated by DB
  title: z.string().min(3, "Title must be at least 3 characters long"),
  description: z.string().min(10, "Description must be at least 10 characters long"),
  price: z.number(),
  isFree: z.boolean(),
  categoryId: z.string().nonempty("Category ID is required"),
  authorId: z.string().nonempty("Author ID is required"),

  thumbnail: z.string().url("Thumbnail must be a valid URL"), 
  overviewUrl: z.string().url("Overview must be a valid URL"),

  tags: z.array(z.string()).default([]),
  features: z.array(z.string()).default([]),
  overviews: z.array(z.string()).default([]),
  stack: z.array(z.string()).default([]),

  isDeleted: z.boolean().default(false),
  createdAt: z.date().optional(),
  updatedAt: z.date().optional(),
});


// ✅ Create and Update schemas
export const createCourseSchema = courseSchema.omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});

export const updateCourseSchema = courseSchema.partial().omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});

